# Generated by Django 4.0.6 on 2022-12-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='examshift',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
