# Generated by Django 4.0.6 on 2023-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addexam_examshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='newappemail',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
