# Generated by Django 4.0.6 on 2023-02-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_newapp_newappemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapp',
            name='newappdepart',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
