# Generated by Django 4.0.6 on 2023-03-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_addexam_newaddexamcentre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexam',
            name='newaddexamcentre',
        ),
        migrations.AddField(
            model_name='addexam',
            name='newaddexamcentre',
            field=models.ManyToManyField(blank=True, to='home.addexamcentre'),
        ),
    ]
