# Generated by Django 4.0.6 on 2023-03-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_addexam_newaddexamcentre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexam',
            name='examcentre',
        ),
    ]
