# Generated by Django 4.0.6 on 2022-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testing_newapp_newappdepart_newapp_newappposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='examaddbuilding',
            field=models.ManyToManyField(blank=True, to='home.addbuilding'),
        ),
    ]
