# Generated by Django 4.0.6 on 2022-10-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
            preserve_default=False,
        ),
    ]
