# Generated by Django 4.0.6 on 2022-10-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_addexam_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexam',
            name='profile',
        ),
    ]
