# Generated by Django 4.0.6 on 2022-10-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_addexam_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexam',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
