# Generated by Django 4.0.6 on 2022-10-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_addbuilding_profile_addroom_profile_newapp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_user',
            field=models.FileField(default='', upload_to='profile/uploaded_files/'),
            preserve_default=False,
        ),
    ]
