# Generated by Django 4.0.6 on 2022-10-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbuilding',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='addexam',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='addroom',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='newapp',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
