# Generated by Django 4.0.6 on 2022-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file_user',
            field=models.FileField(blank=True, null=True, upload_to='profile/uploaded_files/'),
        ),
    ]
