# Generated by Django 4.0.6 on 2022-10-30 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0018_alter_profile_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='name',
        ),
        migrations.AddField(
            model_name='testing',
            name='file_generated',
            field=models.FileField(blank=True, null=True, upload_to='profile/generated_files/'),
        ),
        migrations.AddField(
            model_name='testing',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
