# Generated by Django 4.0.6 on 2022-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_testing_name_testing_file_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_generated',
            field=models.FileField(blank=True, null=True, upload_to='profile/generated_files/'),
        ),
    ]
