# Generated by Django 4.0.6 on 2022-10-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_profile_file_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbuilding',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.AddField(
            model_name='addexam',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.AddField(
            model_name='addroom',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.AddField(
            model_name='newapp',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
